<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260712130755 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE loyalty_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, balance INT DEFAULT 0 NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11F7BE17A76ED395 ON loyalty_account (user_id)');
        $this->addSql('CREATE TABLE loyalty_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, points INT NOT NULL, balance_after_transaction INT NOT NULL, loyalty_account_id INT NOT NULL, order_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4CE4AEC126B7945D ON loyalty_transaction (loyalty_account_id)');
        $this->addSql('CREATE INDEX IDX_4CE4AEC18D9F6D38 ON loyalty_transaction (order_id)');
        $this->addSql('CREATE TABLE "order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F5299398A76ED395 ON "order" (user_id)');
        $this->addSql('ALTER TABLE loyalty_account ADD CONSTRAINT FK_11F7BE17A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE loyalty_transaction ADD CONSTRAINT FK_4CE4AEC126B7945D FOREIGN KEY (loyalty_account_id) REFERENCES loyalty_account (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE loyalty_transaction ADD CONSTRAINT FK_4CE4AEC18D9F6D38 FOREIGN KEY (order_id) REFERENCES "order" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F5299398A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE loyalty_account DROP CONSTRAINT FK_11F7BE17A76ED395');
        $this->addSql('ALTER TABLE loyalty_transaction DROP CONSTRAINT FK_4CE4AEC126B7945D');
        $this->addSql('ALTER TABLE loyalty_transaction DROP CONSTRAINT FK_4CE4AEC18D9F6D38');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F5299398A76ED395');
        $this->addSql('DROP TABLE loyalty_account');
        $this->addSql('DROP TABLE loyalty_transaction');
        $this->addSql('DROP TABLE "order"');
    }
}
